version: "3"
services:
  animeshmongodb:
    image: mongo:latest
    container_name: animeshmongodb
    ports:
      - 27017:27017
  docker_restapi_test:
    image: docker_restapi_test:1.0
    container_name: docker_restapi_test
    ports:
      - 8080:8080
    links:
      - animeshmongodb